import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { prisma } from "@/lib/supabase/db";
import { ThemeProvider } from "@/lib/provider/theme-provider";
import {DM_Sans} from 'next/font/google';


const geistSans = DM_Sans({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("Prisma Client:", prisma.$connect().then(() => {
    console.log("Prisma Client connected successfully");
  }).catch((error) => {
    console.error("Error connecting Prisma Client:", error);
  }));

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.className} bg-background`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >


        {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
